/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javafx.util.Pair;
import virusexpansion.Simulacion;

/**
 *
 * @author Santiago Pérez Gómez
 */
public class CargaParametrosGenerales extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private Simulacion simulacion;

    /**
     * Creates new form CargaParametros
     */
    public CargaParametrosGenerales(java.awt.Frame parent, Simulacion simulacion) {
        //super(parent, true);
        this.parent = parent;
        this.simulacion = simulacion;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloParametros = new javax.swing.JLabel();
        labelNumDias = new javax.swing.JLabel();
        labelViajeros = new javax.swing.JLabel();
        labelE = new javax.swing.JLabel();
        labelP = new javax.swing.JLabel();
        labelNumComunidades = new javax.swing.JLabel();
        textFieldNumDias = new javax.swing.JTextField();
        textFieldViajeros = new javax.swing.JTextField();
        textFieldE = new javax.swing.JTextField();
        textFieldP = new javax.swing.JTextField();
        textFieldNumComunidades = new javax.swing.JTextField();
        botonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TituloParametros.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        TituloParametros.setText("Introduzca los datos indicados necesarios para ejecutar la simulación:");

        labelNumDias.setText("Número de días:");

        labelViajeros.setText("Porcentaje de Viajeros (V):");

        labelE.setText("Nº promedio de contactos con infectados (E):");

        labelP.setText("Probabilidad de contagio (P):");

        labelNumComunidades.setText("Número de comunidades:");

        textFieldNumDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNumDiasKeyTyped(evt);
            }
        });

        textFieldViajeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldViajerosKeyTyped(evt);
            }
        });

        textFieldE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldEKeyTyped(evt);
            }
        });

        textFieldP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldPKeyTyped(evt);
            }
        });

        textFieldNumComunidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNumComunidadesKeyTyped(evt);
            }
        });

        botonOk.setText("Aceptar");
        botonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonOk)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelViajeros)
                                    .addComponent(labelE)
                                    .addComponent(labelNumDias)
                                    .addComponent(labelP)
                                    .addComponent(labelNumComunidades))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldViajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNumComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloParametros)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TituloParametros)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumDias)
                    .addComponent(textFieldNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelViajeros)
                    .addComponent(textFieldViajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelE)
                    .addComponent(textFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelP)
                    .addComponent(textFieldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumComunidades)
                    .addComponent(textFieldNumComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
        String numDiasString = this.textFieldNumDias.getText();
        String porcentajeViajerosString = this.textFieldViajeros.getText();
        String coeficienteEString = this.textFieldE.getText();
        String coeficientePString = this.textFieldP.getText();
        String numComunidadesString = this.textFieldNumComunidades.getText();
        if (!numDiasString.isEmpty() && !porcentajeViajerosString.isEmpty() && !coeficienteEString.isEmpty()
                && !coeficientePString.isEmpty() && !numComunidadesString.isEmpty()) {
            int numDias = Integer.valueOf(numDiasString);
            double porcentajeViajeros = Double.valueOf(porcentajeViajerosString);
            double coeficienteE = Double.valueOf(coeficienteEString);
            double coeficienteP = Double.valueOf(coeficientePString);
            int numComunidades = Integer.valueOf(numComunidadesString);
            simulacion.cargarParametrosFrontGenerales(numDias, porcentajeViajeros, coeficienteE, coeficienteP, numComunidades);
            // Se abre la ventana para insertar los parámetros de la simulación
            CargarParametrosComunidad formVerParametrosComunidad = new CargarParametrosComunidad(parent, simulacion.getComunidades().length, 0, simulacion,
                    new ArrayList<Pair<String, Double>>());
            formVerParametrosComunidad.setVisible(true);
            formVerParametrosComunidad.setLocationRelativeTo(null);
            this.setVisible(false);
        }

    }//GEN-LAST:event_botonOkActionPerformed

    private void textFieldNumDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNumDiasKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_textFieldNumDiasKeyTyped

    private void textFieldPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            if (c == '.') {
                int cont = 0;
                String text = this.textFieldP.getText();
                for (int i = 0; i < text.length(); i++) {
                    if (text.charAt(i) == '.') {
                        cont++;
                    }
                }
                if (cont > 0 || text.isEmpty()) {
                    getToolkit().beep();
                    evt.consume();
                }
            } else {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_textFieldPKeyTyped

    private void textFieldViajerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldViajerosKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            if (c == '.') {
                int cont = 0;
                String text = this.textFieldViajeros.getText();
                for (int i = 0; i < text.length(); i++) {
                    if (text.charAt(i) == '.') {
                        cont++;
                    }
                }
                if (cont > 0 || text.isEmpty()) {
                    getToolkit().beep();
                    evt.consume();
                }
            } else {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_textFieldViajerosKeyTyped

    private void textFieldEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldEKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            if (c == '.') {
                int cont = 0;
                String text = this.textFieldE.getText();
                for (int i = 0; i < text.length(); i++) {
                    if (text.charAt(i) == '.') {
                        cont++;
                    }
                }
                if (cont > 0 || text.isEmpty()) {
                    getToolkit().beep();
                    evt.consume();
                }
            } else {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_textFieldEKeyTyped

    private void textFieldNumComunidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNumComunidadesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_textFieldNumComunidadesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloParametros;
    private javax.swing.JButton botonOk;
    private javax.swing.JLabel labelE;
    private javax.swing.JLabel labelNumComunidades;
    private javax.swing.JLabel labelNumDias;
    private javax.swing.JLabel labelP;
    private javax.swing.JLabel labelViajeros;
    private javax.swing.JTextField textFieldE;
    private javax.swing.JTextField textFieldNumComunidades;
    private javax.swing.JTextField textFieldNumDias;
    private javax.swing.JTextField textFieldP;
    private javax.swing.JTextField textFieldViajeros;
    // End of variables declaration//GEN-END:variables

}
