/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import virusexpansion.Simulacion;

/**
 *
 * @author Santiago Pérez Gómez
 */
public class Inicio extends javax.swing.JFrame {

    Simulacion simulacion;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfc = new javax.swing.JFileChooser();
        botonParametros = new javax.swing.JButton();
        labelTitulo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonSimulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonParametros.setText("Cargar Parámetros");
        botonParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParametrosActionPerformed(evt);
            }
        });

        labelTitulo1.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        labelTitulo1.setText("VirusEvolution: ");

        jLabel2.setText("Simulación de la evolución de contagios en una pandemia");

        botonSimulacion.setText("Iniciar Simulación");
        botonSimulacion.setEnabled(false);
        botonSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonParametros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(labelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonParametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSimulacion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParametrosActionPerformed
        // Se abre la ventana para insertar los parámetros de la simulación
        simulacion = new Simulacion();
        CargaParametrosGenerales formVerParametrosGenerales = new CargaParametrosGenerales(this, simulacion);
        formVerParametrosGenerales.setVisible(true);
        formVerParametrosGenerales.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_botonParametrosActionPerformed

    private void botonSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimulacionActionPerformed
         //Se obtiene la ruta de donde se quiere almacenar el fichero y se guarda
        String ruta;
        try {
            jfc.setSelectedFile(new File("VirusEvolutionSimulation.xlsx"));
            if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                ruta = jfc.getSelectedFile().getAbsolutePath();
                simulacion.iniciarSimulacion(ruta);
                JOptionPane.showMessageDialog(this, "Simulación finalizada correctamente.", "Información",
                JOptionPane.INFORMATION_MESSAGE);
                this.botonIniciarDisabled();
            }
        } catch (HeadlessException ex) {
            System.out.println("Error al obtener el directorio para almacenar la clasificación");
        }
        
    }//GEN-LAST:event_botonSimulacionActionPerformed

    public void botonIniciarEnabled(){
        this.botonSimulacion.setEnabled(true);
        this.botonParametros.setEnabled(false);
    }
   
    public void botonIniciarDisabled(){
        this.botonSimulacion.setEnabled(false);
        this.botonParametros.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonParametros;
    private javax.swing.JButton botonSimulacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFileChooser jfc;
    private javax.swing.JLabel labelTitulo1;
    // End of variables declaration//GEN-END:variables
}
